### ISSUE TITLE
Cant Brew Anything

### ISSUE THREAD

**Issue by SnowfireAnimation** [DieReicheErethons/Brewery#235] opened 2020-01-10 09:06 UTC
A few friends and i have added Brewery to our server, however every time we distill anything, it becomes murky distillate, and every time we try and age something it becomes a ruined potion.  I know we are following the recipe correctly, but we cant get anything to work.  Thanks.

**Comment by Sn0wStorm** [comment] 2020-01-24 13:14
Make sure you add enough ingredients into the cauldron and keep the cauldron boiling for long enough with all ingredients inside.
What does the Brew look like right after taking it out of the Cauldron?

**Comment by Shedopen** [comment] 2020-03-18 19:54
I have exacly the same problem, no recipe is working anymore

**Comment by DJLost12** [comment] 2020-03-24 16:31
Confirmed. With only brewery plugin. On paper 1.15.2,  all cauldron parts work. Ant brewing stand part turns the fermented item into murky distillate

**Comment by Sn0wStorm** [comment] 2020-03-24 19:56
Please do /brew reload
What does it say when you do that?

If nothing else works, try to delete your config.yml and let it generate a new one, does it work then?

**Comment by DJLost12** [comment] 2020-03-24 20:19
Hi,

Brew reload works without issue. Here are the steps I’ve tried.

1. Added brewery and restarted server
2. Used commands to create nearly all of the current recipes.
3. Gave drinks to multiple players as a test. Everything working fine
4. Tested cooking features sugarcane, potatoes etc. all worked to give the
expected fermented item.
5. Placed multiple types of fermented items in brewing stand. All yielded
only murky distillate
6. Added brewery to test server with only the plugin and new world. Paper
1.15.2
7. Everything worked perfectly. Added copy of all plugins. Brewing stand
again yielded murky distillate
8. Removed all plugins one by one, restarted. Tested. In each case brewing
stand yielded murky distillate. Including when the only plugin on the test
server was brewery.

Would mcmmo, jobs, protocollib or any other commonly used plugin change
something in the world to cause this?

**Comment by DJLost12** [comment] 2020-03-24 23:17
I can forward the entire file when I get off work. This is the best I can
do from my phone

**Comment by Sn0wStorm** [comment] 2020-03-25 08:43
Thank you so much for your testing so far.
So it seems like some other plugin is changing the Server so that afterwards the brewing doesn't work anymore?
I don't know of any plugin that could even do that, so we need to find out which plugin does it

**Comment by yntel** [comment] 2020-03-29 12:59
I'm having the same issue running Paper 1.15.2. No log output giving me any idea what's going on. By the looks of things, many other people are experiencing this bug. @Sn0wStorm does this still need reproduction? Is there anything that needs to be tested to gain further information? Happy to help out in whatever way I can.

**Comment by DJLost12** [comment] 2020-03-29 13:02
Wiped entire config folder with server offline. Regenerated with server restart. tested all brews before editing config in any way. All issues have been resolved for me.

**Comment by yntel** [comment] 2020-03-29 14:24
@DJLost12 I tried this but it didn't work for me. Can you tell me a bit more about your setup? Server version etc?

**Comment by DJLost12** [comment] 2020-03-29 14:26
> @DJLost12 I tried this but it didn't work for me. Can you tell me a bit more about your setup? Server version etc?

tuinity 1.15.2, latest build. latest build of brewery. default configs. aac for anticheat, mcmmo and jobs , latest builds. zero issues after regenerating base configs.

**Comment by yntel** [comment] 2020-03-30 18:56
@DJLost12 Ah okay. i'm running Paper 1.15.2, latest build (149), latest build of brewery. Default configs.

I did what you said, distilling and ageing is still not working for me or my players. I feel like there's some sort of error occurring that I can't work out here.

**Comment by DJLost12** [comment] 2020-03-30 20:16
> @DJLost12 Ah okay. i'm running Paper 1.15.2, latest build (149), latest build of brewery. Default configs.
> 
> I did what you said, distilling and ageing is still not working for me or my players. I feel like there's some sort of error occurring that I can't work out here.

I am available from 1230 am till 5 am through the week. And. I can make time on the weekends. If you would like, I can drop by your server. We can see if two heads are better than one.

**Comment by yntel** [comment] 2020-03-31 07:53
@DJLost12 it would be great to work together and troubleshoot this thing. I'm in time zone GMT. Where are you based? You can reach me on Discord - my code is Kwikxilver#6241

**Comment by yntel** [comment] 2020-03-31 21:56
Ok - @DJLost12 and I troubleshooted this thing for a while, and we figured out the issue in the end. It was a conflict with a plugin I had installed called CivModCore-1.7.8.jar. It's a coremod for a suite of plugins tailored for a specific server, that it turns out I didn't need. Something in the mod messed with potion recipes or messed with Brewery specifically, which meant that trying to age or distill anything didn't work.

Removing CivModCore fixed all issues and it seems we're able to brew again as normal. I'm not sure exactly what caused this issue though...

**Comment by Sn0wStorm** [comment] 2020-04-01 20:10
Thats a great find @DJLost12 and @yntel Thank you for your research!
I'll load CivModCore on my test server to see if i can reproduce the issue and find out whats causing it.
I remember that the developers of that plugin had a plugin called Citadel and they added support for Brewery. Maybe it has something to do with that, but i'll try and find out.

**Comment by Sn0wStorm** [comment] 2020-04-02 12:10
I could only find the Version 1.7.5 of CivModCore, with that version it seems to work fine from what i can tell.
Where did you get 1.7.8 from?

**Comment by Sn0wStorm** [comment] 2020-04-02 18:32
Ive tried different versions of CivModCore, 1.7.7, compiled some versions of 1.7.8 also tried Jobs, ProtocolLib, Vault but no matter what i did the Distilling always worked just fine. Maybe you could give me a list of plugins to test?
Or tell me where you got the CivModCore from

**Comment by Scarlet-Hunter** [comment] 2020-04-13 11:07
Hey. I still have this exact issue but I'm not running that plugin. I really enjoy Brewery but no matter what I do I can't seem to fix it. Please can you help?

Thank you

**Comment by Sn0wStorm** [comment] 2020-04-13 11:33
Could you send me a list of your plugins?

**Comment by Sn0wStorm** [comment] 2020-04-13 12:34
And maybe if anyone has the time enable debug: true in the config
and paste here what it outputs when a barrel or distiller ruins a brew that should'nt be ruined

**Comment by Scarlet-Hunter** [comment] 2020-04-13 16:16
As for the barrels the console is spammed with 'unscrambled data':
BreweryRunnable: t1: 0.01008ms | t2: 0.03787ms | t3: 4.57E-4ms | t4: 0.005313ms | t5: 1.64E-4ms
13.04 09:12:28 [Server] INFO [Debug] Unscrambled data
13.04 09:12:28 [Server] INFO [Debug] Unscrambled data
13.04 09:12:28 [Server] INFO [Debug] Unscrambled data
13.04 09:12:28 [Server] INFO [Debug] Unscrambled data
13.04 09:12:28 [Server] INFO [Debug] Unscrambled data
13.04 09:12:28 [Server] INFO [Debug] Unscrambled data
13.04 09:12:28 [Server] INFO [Debug] Unscrambled data
13.04 09:12:28 [Server] INFO [Debug] Unscrambled data
13.04 09:12:28 [Server] INFO [Debug] Unscrambled data
13.04 09:12:28 [Server] INFO [Debug] opening Barrel with potions (0.824351ms)
13.04 09:12:31 [Server] INFO [Debug] Unscrambled data
13.04 09:12:31 [Server] INFO [Debug] Unscrambled data
13.04 09:12:32 [Server] INFO [Debug] Unscrambled data

In the brewing stand all it says is that:
Can distill more! Continuing.
13.04 09:14:26 [Server] INFO [Debug] using brewtime: 800
13.04 09:14:28 [Server] INFO [Debug] BreweryRunnable: t1: 0.001766ms | t2: 0.021345ms | t3: 1.54E-4ms | t4: 0.001247ms | t5: 0.011146ms
13.04 09:14:28 [Server] INFO [Debug] saving: 0.176227ms

I can send you a list of plugins but most of them are custom and made by my Dev.

**Comment by Scarlet-Hunter** [comment] 2020-04-13 16:17
Also when taking the potions out of the brewing stand it says the exact same 'unscrambled data'.

**Comment by Sn0wStorm** [comment] 2020-04-13 19:06
Hm nothing out of the ordinary, Unscrambled data is unrelated, thats just when it reads data of the potions.
Before "using Brewtime" it should say which recipe it is going to favor, here it says nothing, so it just doesn't find any matching recipe..

I just can't reproduce this on my server, i'll add an item debug info command to the next update, maybe that will help here.


What we know from @DJLost12 here https://github.com/DieReicheErethons/Brewery/issues/235#issuecomment-603483408

1. Brewery on a clean Server and World works fine.
2. Adding other Plugins breaks Distilling and/or Aging
3. Removing the other Plugins again does not get Brewery to work again.
4. For him removing CivModCore fixed all problems.

@Scarlet-Hunter doesn't have CivModCore but the same problem nonetheless 
I tested different Versions of CivModCore, as well as SlimeFun, Essentials, ProtocolLib, Multiverse etc. and no matter what i do i don't get the Problem.

**Comment by Scarlet-Hunter** [comment] 2020-04-14 10:52
Well for me we've tried it on a clean world spigot and paper and neither works.

**Comment by Sn0wStorm** [comment] 2020-04-15 15:23
> Well for me we've tried it on a clean world spigot and paper and neither works.

That is bad. That means anything could cause this..  
Could you please if that is possible send me the whole Test-Server as a zip? So i can reproduce the issue. It should not contain any personal information if it is only a clean test server?
That would help immensely

**Comment by Scarlet-Hunter** [comment] 2020-04-16 17:06
The file is too big for Github

**Comment by yntel** [comment] 2020-04-16 18:09
@Scarlet-Hunter what about uploading the file through MegaUpload, or Google Drive or Dropbox and just sending the link here?

**Comment by Sn0wStorm** [comment] 2020-04-16 19:29
@Scarlet-Hunter You can upload it here into my cloud if you like: https://zebradrive.de/index.php/s/KiaKIysX4Rr8fT9

**Comment by Scarlet-Hunter** [comment] 2020-04-18 21:16
Its been uploaded

**Comment by Sn0wStorm** [comment] 2020-04-24 20:03
I tested with the server you uploaded and i get Vodka just fine...
What java version (java -version) are you running the server on?

![Bildschirmfoto 2020-04-24 um 22 00 56](https://user-images.githubusercontent.com/4077108/80252324-61e74c80-8677-11ea-9120-b410871603ed.png)

**Comment by mrhacks101** [comment] 2020-04-25 10:02
i have tried to fix the Brewery plugin i have cleared my configs and tried to reinstall the plugin but i still just keep getting failed potions and murky distilled potions

**Comment by Scarlet-Hunter** [comment] 2020-04-27 21:16
We're running version 8

**Comment by Sn0wStorm** [comment] 2020-05-02 09:33
@mrhacks101 @Scarlet-Hunter @yntel 
Could anyone with this problem please try on version 2.1.1 with an item that would turn out ruined or murky:  
Hold the item in hand and run `/brew debuginfo` and `/brew debuginfo Vodka` (or the recipe you were trying to create).  
It should print a lot of info into the server log. Post the output here using hastebin or pastebin

Thank you!

**Comment by Scarlet-Hunter** [comment] 2020-05-03 22:19
https://pastebin.com/CwNqbPHf

That's with what should be Vodka

**Comment by Dolf28** [comment] 2020-05-18 13:19
Hello @Sn0wStorm ,

We wanted to use this plugin on our server. Unfortunately we ran in to the same bug as many before us. We still want this plugin to work because it would fit right into our server. I'll list the output of our bug down below. If you need it i can send you a list of all our plugins, only most of them are custom made by our dev(s). I hope to hear from you soon.

Kind regards,
Dolf

[15:10:50 INFO]: _dolfje28_ issued server command: /brew debuginfo
[15:15:07 WARN]: java.io.NotSerializableException: org.bukkit.Color
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
[15:15:07 WARN]: at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[15:15:07 WARN]: at java.util.ArrayList.writeObject(ArrayList.java:766)
[15:15:07 WARN]: at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
[15:15:07 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:15:07 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[15:15:07 WARN]: at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[15:15:07 WARN]: at java.util.ArrayList.writeObject(ArrayList.java:766)
[15:15:07 WARN]: at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
[15:15:07 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:15:07 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[15:15:07 WARN]: at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[15:15:07 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[15:15:07 WARN]: at net.coreprotect.Functions.convertByteData(Functions.java:259)
[15:15:07 WARN]: at net.coreprotect.database.Database.insertContainer(Database.java:242)
[15:15:07 WARN]: at net.coreprotect.database.Logger.container_logger(Logger.java:144)
[15:15:07 WARN]: at net.coreprotect.database.Logger.log_container(Logger.java:291)
[15:15:07 WARN]: at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:289)
[15:15:07 WARN]: at net.coreprotect.consumer.Process.processConsumer(Process.java:124)
[15:15:07 WARN]: at net.coreprotect.consumer.Consumer.run(Consumer.java:107)
[15:15:07 WARN]: at java.lang.Thread.run(Thread.java:748)
[15:16:11 WARN]: java.io.NotSerializableException: org.bukkit.Color
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
[15:16:11 WARN]: at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[15:16:11 WARN]: at java.util.ArrayList.writeObject(ArrayList.java:766)
[15:16:11 WARN]: at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
[15:16:11 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:16:11 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[15:16:11 WARN]: at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[15:16:11 WARN]: at java.util.ArrayList.writeObject(ArrayList.java:766)
[15:16:11 WARN]: at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
[15:16:11 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:16:11 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[15:16:11 WARN]: at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[15:16:11 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[15:16:11 WARN]: at net.coreprotect.Functions.convertByteData(Functions.java:259)
[15:16:11 WARN]: at net.coreprotect.database.Database.insertContainer(Database.java:242)
[15:16:11 WARN]: at net.coreprotect.database.Logger.container_logger(Logger.java:144)
[15:16:11 WARN]: at net.coreprotect.database.Logger.log_container(Logger.java:290)
[15:16:11 WARN]: at net.coreprotect.consumer.Process.processContainerTransaction(Process.java:289)
[15:16:11 WARN]: at net.coreprotect.consumer.Process.processConsumer(Process.java:124)
[15:16:11 WARN]: at net.coreprotect.consumer.Consumer.run(Consumer.java:107)
[15:16:11 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by gbatdorff** [comment] 2020-05-23 21:11
Hello, I was having the same issue on my paper 1.15.2 server. Switching back to Spigot resolved the issue.

**Comment by Dolf28** [comment] 2020-05-24 09:27
Hi,

We had this issue and now it is semi resolved. We couldn’t ferment or age anything but when we switched back to the 1.8 version of the plugin we were able to age again! (Only still not able to ferment). Does anyone have a solution for this? We have a lot of custom made plugins so sending a plugin list would work.

**Comment by Commandcracker** [comment] 2020-06-03 05:37
check this https://github.com/DieReicheErethons/Brewery/issues/307

**Comment by Dolf28** [comment] 2020-06-03 05:39
@Commandcracker we have the exact opposite problem. Distilling doesn’t work but ageing does

**Comment by Scarlet-Hunter** [comment] 2020-06-22 16:41
@Dolf28 I've tried all I can but it still doesn't work. I still can't distill or age anything and it has been nearly 2 months since I've heard anything from @Sn0wStorm or anyone regarding this so I think it's just not going to be resolved. I'd love to use it but after not hearing anything about the issue for so long and with the update being tomorrow I doubt I can launch my server restart with it. To be honest I doubt it will get updated to 1.16 for a while if ever anyway.

**Comment by Dolf28** [comment] 2020-06-22 16:45
@Scarlet-Hunter yeah, we have decided to take the brewing stand part out entirely so that we can still use it in our server. I’d love to see this being solved but as you said I don’t have high hopes.

**Comment by Sn0wStorm** [comment] 2020-06-23 13:01
The Problem is that it seems very hard to reproduce this bug. It works fine on all my testing servers.

There are many conflicting reports, for some the distilling doesn't work, for some the ageing, for some both, leading me to believe that it might even be two different issues.
Some have fixed it by removing CivModCore, others ShopKeepers.

The log i've got from Scarlet-Hunter clearly shows a bug with how the ingredients are stored on the items. But others have reported the issue to appear after changing the World Time.

So yeah it will probably keep taking me a while to figure this out.

**Comment by Enderminer** [comment] 2020-07-31 01:05
Having the same issue with the mod using version 2.1.1. on Paper for 1.16.
Every single time we leave fermented wheat inside a large barrel for a bit and watch it it just turns into a ruined potion.

Here's the output on the ruined potion in debug info:
`[00:55:53] [Server thread/INFO]: /brewery
[00:55:53] [Server thread/INFO]: [Brewery] Brew{BIngredients{cookedTime=8, total ingredients: 0} ingredients, quality=0, alc=0, distillRuns=0, ageTime=0.75000006, wood=1.0, currentRecipe=null, unlabeled=false, immutable=false, stripped=false}
[00:55:53] [Server thread/INFO]: [Brewery] Ingredients:
[00:55:53] [Server thread/INFO]: [Brewery] Testing Recipes
[00:55:53] [Server thread/INFO]: [Brewery] Example: ingQlty: -1, cookQlty:-1, cook+DistQlty: 2
[00:55:53] [Server thread/INFO]: [Brewery] Wheatbeer: ingQlty: -1, cookQlty:10, cook+DistQlty: -1
[00:55:53] [Server thread/INFO]: [Brewery] Beer: ingQlty: -1, cookQlty:10, cook+DistQlty: -1
[00:55:53] [Server thread/INFO]: [Brewery] Darkbeer: ingQlty: -1, cookQlty:10, cook+DistQlty: -1
[00:55:53] [Server thread/INFO]: [Brewery] Red Wine: ingQlty: -1, cookQlty:5, cook+DistQlty: -1
[00:55:53] [Server thread/INFO]: [Brewery] Mead: ingQlty: -1, cookQlty:3, cook+DistQlty: -1
[00:55:53] [Server thread/INFO]: [Brewery] Sweet Apple Mead: ingQlty: -1, cookQlty:3, cook+DistQlty: -1
[00:55:53] [Server thread/INFO]: [Brewery] Apple Cider: ingQlty: -1, cookQlty:8, cook+DistQlty: -1
[00:55:53] [Server thread/INFO]: [Brewery] Apple Liquor: ingQlty: -1, cookQlty:-1, cook+DistQlty: 2
[00:55:53] [Server thread/INFO]: [Brewery] Whiskey: ingQlty: -1, cookQlty:-1, cook+DistQlty: 5
[00:55:53] [Server thread/INFO]: [Brewery] Spicy Rum: ingQlty: -1, cookQlty:-1, cook+DistQlty: 5
[00:55:53] [Server thread/INFO]: [Brewery] Vodka: ingQlty: -1, cookQlty:-1, cook+DistQlty: 4
[00:55:53] [Server thread/INFO]: [Brewery] Mushroom Vodka: ingQlty: -1, cookQlty:-1, cook+DistQlty: -1
[00:55:53] [Server thread/INFO]: [Brewery] Gin: ingQlty: -1, cookQlty:-1, cook+DistQlty: 5
[00:55:53] [Server thread/INFO]: [Brewery] Tequila: ingQlty: -1, cookQlty:-1, cook+DistQlty: 2
[00:55:53] [Server thread/INFO]: [Brewery] Absinthe: ingQlty: -1, cookQlty:-1, cook+DistQlty: -1
[00:55:53] [Server thread/INFO]: [Brewery] Green Absinthe: ingQlty: -1, cookQlty:-1, cook+DistQlty: -1
[00:55:53] [Server thread/INFO]: [Brewery] Potato soup: ingQlty: -1, cookQlty:4, cook+DistQlty: -1
[00:55:53] [Server thread/INFO]: [Brewery] Coffee: ingQlty: -1, cookQlty:0, cook+DistQlty: -1
[00:55:53] [Server thread/INFO]: [Brewery] Eggnog: ingQlty: -1, cookQlty:0, cook+DistQlty: -1
[00:55:53] [Server thread/INFO]: [Brewery] Would prefer Recipe: none and Distill-Recipe: none`

**Comment by Sn0wStorm** [comment] 2020-11-04 11:02
#335

**Comment by Sn0wStorm** [comment] 2020-12-14 12:26
Fixed in v3.0

**Closed by Sn0wStorm** 2020-12-14 12:26 UTC
Labels: Bug, Historic
