### ISSUE TITLE
Errors which spam with MMOItem

### ISSUE THREAD

**Issue by Yukyxy** [DieReicheErethons/Brewery#253] opened 2020-03-28 11:32 UTC
Hi,
I report to you an error generated by mmoitem when using brewery (https://pastebin.com/mueQAtFE) (my server is in 1.15.2), this is generated by each addition of ingredients in the cauldron, which do a huge spam in the console (since several months)... This occurs even if we have no mmoitem put in the brewery config. I have the impression that this is an API problem (that of mmoitem must have changed), could you do a version please which corrects this problem that we have as a user of mmoitem (Feldmarrschall mention this problem too also in spigot discussion) or add a line true or false (as for you did for the protection plugins) to activate and deactivate this integration in case or if mmoitem still changes somethings, again avoiding the generation of error.

Thank you in advance for your answer and this fix.

**Comment by Sn0wStorm** [comment] 2020-04-02 15:49
The Issue is fixed now. If they should update something again in the future, the error will only appear once and then it will automatically disable any MMOItems checking.

**Closed by Sn0wStorm** 2020-04-02 15:49 UTC
