### ISSUE TITLE
can't use exoticgarden (slimefun) items anymore

### ISSUE THREAD

**Issue by mrcoffee1026** [DieReicheErethons/Brewery#277] opened 2020-04-15 23:38 UTC
Had recipes these worked with before, since update these recipes won't work as the items can not be added to cauldrons anymore even if they are specified in the config properly
Example:
    ingredients:
      - Wheat/8
      - ExoticGarden:Lime/1

version 2.1.1

**Comment by mcgodbuild** [comment] 2020-04-16 08:09
Did you add the correct /brew iteminfo data to the custom materials part of the top of the config? Any non vanilla item needs to be added as a custom material before it can become a cauldron ingredient or a recipe material.

I to noticed the config file changed the lay-out after the update as it would not take the config file from the old version to the updated version. I fixed that by copy pasting all the recipes to the new fresh config file.

**Comment by mrcoffee1026** [comment] 2020-04-16 13:14
Can't do that since it's already defined in the plugin properly as an exoticgarden item.  If I were to use the brewery custom item method to explain what the item is, then it is just a "player_head", thereby eliminating this item for every other slimefun ingredient that is used in other recipes.  Again, this worked in a previous version, it is properly set up.

**Comment by Sn0wStorm** [comment] 2020-04-16 18:42
Have you also updated Slimefun? Maybe they just changed something in their api?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mrcoffee1026** [comment] 2020-04-16 18:46
I do keep slimefun fully updated with the latest working build, there have been updates made to it since this had once worked, so if something needs to be changed to this plugin to work with the altered api to make it work again, then it would just need to be updated accordingly although I don't know what needs to be done to it, I  just know it's not working now.  I may test and see if the version of brewery 2 releases ago still works since it used to although I'll test local, not on the live server... and let you know what I find out.

**Comment by Sn0wStorm** [comment] 2020-04-16 18:51
Ok thank you for testing! I don’t remember changing anything in regards to the Slimefun support, so i’d be surprised if it works with an old version but not the new one

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mrcoffee1026** [comment] 2020-04-16 18:58
Yes verified I cannot place the slimefun items in the cauldron even though they had previously worked in version 2.0.1, they don't work any more.  So if you want to continue to say you support items from Slimefun & ExoticGarden, an update on this end will need to be made.

**Comment by Sn0wStorm** [comment] 2020-04-16 19:22
All right, good to know. I will take a look and update, but I hope nothing breaks again in the future

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mrcoffee1026** [comment] 2020-04-16 19:24
I don't think they update the API THAT frequently but I know a recent update did deal with exactly that:

https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/#478

So this probably broke all references to slimefun/exoticgarden items in recipes.. not sure how they changed it but you can probably give it a look there if it helps.

**Comment by Sn0wStorm** [comment] 2020-04-16 19:32
If thats the case i might wait a little longer, as it looks like they are still in the process of changing things. The last refractoring commit was only yesterday

**Comment by mrcoffee1026** [comment] 2020-04-16 19:48
they never finish, the plugin is updated constantly.

**Comment by mrcoffee1026** [comment] 2020-04-17 13:49
Please don't wait very long, that's broken a lot of our recipes and that's the first time they've messed with the API in something like a year, I wouldn't expect them to be making a lot of additional changes to it.

**Comment by TheBusyBiscuit** [comment] 2020-04-25 09:43
I wanna note that the API (at least that part) of Slimefun never changed.
I tried to reproduce this behaviour and found out that most Slimefun items actually worked flawlessly, items from Addons too.

However somehow Grapes, Raspberry etc... (exactly the stuff you'd use to brew drinks) doesn't.
One thing I found very odd though was the fact that when this happens Brewery didn't even attempt to check whether they are a SlimefunItem or not, somehow this check is just skipped. But only for some items. So that was really odd and there must've been some reason as to why these items get ignored.

From there on it took me some time to find the thing that segregates these items from the ones that do work. It turns out that any Item which you can eat is ignored from Brewery.
The reason for that is because ExoticGarden cancels the PlayerInteractEvent when you try to eat a textured head to prevent the Head from being placed down.
Brewery however ignores any cancelled PlayerInteractEvent which is expected and probably also rightful behaviour.
Now it's just a matter of working out a compromise between those two Events battling each other.
I will probably just add a special case to ExoticGarden to __not__ cancel the Event if a Cauldron or any interactable block for that matter was interacted with.

P.S: I only just found out that Brewery even had an integration with Slimefun and I feel like Brewery should be listed on the "addons" page of the Slimefun wiki since they work together (disregarding this bug at least XD). @Sn0wStorm Do you perhaps have discord or any other preferred way of contacting you?

**Comment by TheBusyBiscuit** [comment] 2020-04-25 09:57
Fixed in ExoticGarden DEV - 40

**Comment by Sn0wStorm** [comment] 2020-04-25 11:52
Thank you for your reply, it is very much appreciated that you looked into that.

Ive also had similar issues with integrating MMOItems, as their listener cancels the event so i had to put in a separate listener for that special case [IntegrationListener](https://github.com/DieReicheErethons/Brewery/blob/5cc7116aee854b2ecc1486002e560ad128160b9a/src/com/dre/brewery/integration/IntegrationListener.java#L221)
But in their case, me cancelling the event afterwards and them still handling the cancelled event causes one item to go in to the cauldron and one to be eaten at the same time. Nothing really i can do about that.
Listening to cancelled events on our side would cause Players to be able to use Cauldrons protected by plugins and maybe other problems.
So integrating other plugins is not always straight forward.

Thank you for fixing it, if there is anything i can do to make it easier, please let me know. My Discord is Sn0wStorm. And it would be great if you would add Brewery to the addons page :)

**Comment by mrcoffee1026** [comment] 2020-04-25 19:18
Thanks @TheBusyBiscuit  and everyone who helped look into this :D

**Comment by TheBusyBiscuit** [comment] 2020-04-26 09:47
@mrcoffee1026 No problem :)

@Sn0wStorm On Discord I would need your user id, it's formatted like this Name#ID, otherwise I cannot add you since there could theoretically be multiple accounts holding that name.
Mine is TheBusyBiscuit#2610 if you wanna add me that way.
And cool, will add Brewery there then :)

Yeah, I figured that this was the intention behind it, I would rather avoid adding such special cases or workarounds hence why I rather made them not cancel the Event if an interactable Block was clicked. This wouldn't even alter the behaviour since no block is placed in that scenario anyway.

**Comment by sadbri** [comment] 2020-07-02 12:35
I understand that this was an issue. Im having a similar issue with finding the item id of a magnet it just comes up with a player head#1w and a load if metadata. How do i add this into the config if anyone else has successfully done this. Thanks

**Comment by mrcoffee1026** [comment] 2020-07-03 16:53
I believe the appropriate way should be:
- Slimefun:Magnet/3
Although I've only used ExoticGarden: items so far.

**Comment by Sn0wStorm** [comment] 2020-10-31 15:58
@TheBusyBiscuit Thanks for adding Brewery to the Addons list. My Discord is Sn0wStorm#9422  
Just added you on there.

**Closed by Sn0wStorm** 2020-10-31 15:58 UTC
Labels: Bug
